# Generated by Django 3.2 on 2021-04-15 09:31

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(upload_to='input')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageLabel', models.CharField(max_length=100)),
                ('imageFile', models.ImageField(upload_to=myApp.models.content_file_name)),
            ],
        ),
    ]
