# Generated by Django 3.2.2 on 2021-05-13 08:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210506_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\admion\\Desktop\\project\\imagebase\\model/custom'), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='custommodelfiles',
            name='files',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\admion\\Desktop\\project\\imagebase\\model/custom'), upload_to=''),
        ),
    ]
